
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPrightUMINUSCOMMA EQUALS EVAL FUNCTION ID LPAREN NUMBER OP PIPE RPAREN SEMICOLON STRINGstatement : EVAL ID EQUALS expressionstatement : expression SEMICOLONexpression : PIPE expressionexpression : expression OP expression\n                  | LPAREN expression RPARENexpression : OP expression %prec UMINUSexpression : NUMBERexpression : STRINGexpression : FUNCTION LPAREN arg_list RPARENarg_list : arg_list COMMA expression\n                | expressionexpression : ID'
    
_lr_action_items = {'EVAL':([0,],[2,]),'PIPE':([0,5,6,7,13,17,18,25,],[5,5,5,5,5,5,5,5,]),'LPAREN':([0,5,6,7,10,13,17,18,25,],[7,7,7,7,17,7,7,7,7,]),'OP':([0,3,4,5,6,7,8,9,13,14,15,16,17,18,19,20,22,23,24,25,26,],[6,-12,13,6,6,6,-7,-8,6,13,-6,13,6,6,-4,-5,13,13,-9,6,13,]),'NUMBER':([0,5,6,7,13,17,18,25,],[8,8,8,8,8,8,8,8,]),'STRING':([0,5,6,7,13,17,18,25,],[9,9,9,9,9,9,9,9,]),'FUNCTION':([0,5,6,7,13,17,18,25,],[10,10,10,10,10,10,10,10,]),'ID':([0,2,5,6,7,13,17,18,25,],[3,11,3,3,3,3,3,3,3,]),'$end':([1,3,8,9,12,14,15,19,20,23,24,],[0,-12,-7,-8,-2,-3,-6,-4,-5,-1,-9,]),'SEMICOLON':([3,4,8,9,14,15,19,20,24,],[-12,12,-7,-8,-3,-6,-4,-5,-9,]),'RPAREN':([3,8,9,14,15,16,19,20,21,22,24,26,],[-12,-7,-8,-3,-6,20,-4,-5,24,-11,-9,-10,]),'COMMA':([3,8,9,14,15,19,20,21,22,24,26,],[-12,-7,-8,-3,-6,-4,-5,25,-11,-9,-10,]),'EQUALS':([11,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,5,6,7,13,17,18,25,],[4,14,15,16,19,22,23,26,]),'arg_list':([17,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> EVAL ID EQUALS expression','statement',4,'p_statement_eval','parser_eval.py',21),
  ('statement -> expression SEMICOLON','statement',2,'p_statement','parser_eval.py',26),
  ('expression -> PIPE expression','expression',2,'p_expression_statement','parser_eval.py',30),
  ('expression -> expression OP expression','expression',3,'p_expression_binop','parser_eval.py',34),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_binop','parser_eval.py',35),
  ('expression -> OP expression','expression',2,'p_expression_uminus','parser_eval.py',45),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser_eval.py',49),
  ('expression -> STRING','expression',1,'p_expression_string','parser_eval.py',53),
  ('expression -> FUNCTION LPAREN arg_list RPAREN','expression',4,'p_expression_function','parser_eval.py',57),
  ('arg_list -> arg_list COMMA expression','arg_list',3,'p_arg_list','parser_eval.py',62),
  ('arg_list -> expression','arg_list',1,'p_arg_list','parser_eval.py',63),
  ('expression -> ID','expression',1,'p_expression_id','parser_eval.py',70),
]
